### ISSUE TITLE
Error in example 

### ISSUE THREAD

**Issue by SamVerschueren** [beatfreaker/text-meme-cli#2]
The doube quotes are wrong in the example, as well as a typo in the `background` flag.

```
$ text-meme "Don't forget to be awesome --filename=quote --backgrund=#4f656d"
```

And I think (might be wrong though) that you should place quotes around the hex color.

**Comment by beatfreaker** [comment]
> And I think (might be wrong though) that you should place quotes around the hex color.

how this will be helpful?

**Comment by SamVerschueren** [comment]
Tested it out, it's only necessary if you don't use the `=`. So the example should work without double quotes.

```
text-meme "Don't forget to be awesome" --filename quote --background "#4f656d"
text-meme "Don't forget to be awesome" --filename=quote --background=#4f656d
```

**Comment by beatfreaker** [comment]
:+1:
